//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Grapecity.Internship.Assignment.Calculator.ConsoleApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Grapecity.Internship.Assignment.Calculator.ConsoleApp.Properties.StringResource", typeof(StringResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addition.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arithmetic Binary Operations.
        /// </summary>
        internal static string BinaryOperations {
            get {
                return ResourceManager.GetString("BinaryOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your choice: .
        /// </summary>
        internal static string Choice {
            get {
                return ResourceManager.GetString("Choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cosine.
        /// </summary>
        internal static string Cos {
            get {
                return ResourceManager.GetString("Cos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Division.
        /// </summary>
        internal static string Divide {
            get {
                return ResourceManager.GetString("Divide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to exit? Press 1 otherwise 0.
        /// </summary>
        internal static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exponent.
        /// </summary>
        internal static string Exponent {
            get {
                return ResourceManager.GetString("Exponent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for using the application. See you soon!.
        /// </summary>
        internal static string GoodByeMessage {
            get {
                return ResourceManager.GetString("GoodByeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter valid option.
        /// </summary>
        internal static string InvalidOption {
            get {
                return ResourceManager.GetString("InvalidOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Base e.
        /// </summary>
        internal static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log Base 10.
        /// </summary>
        internal static string Log10 {
            get {
                return ResourceManager.GetString("Log10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multiplication.
        /// </summary>
        internal static string Multiply {
            get {
                return ResourceManager.GetString("Multiply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Number: .
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter First Number.
        /// </summary>
        internal static string Number1 {
            get {
                return ResourceManager.GetString("Number1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Second Number.
        /// </summary>
        internal static string Number2 {
            get {
                return ResourceManager.GetString("Number2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select appropriate option.
        /// </summary>
        internal static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Percentage.
        /// </summary>
        internal static string Percent {
            get {
                return ResourceManager.GetString("Percent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reciprocal.
        /// </summary>
        internal static string Reciprocal {
            get {
                return ResourceManager.GetString("Reciprocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The result is: .
        /// </summary>
        internal static string Result {
            get {
                return ResourceManager.GetString("Result", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sine.
        /// </summary>
        internal static string Sin {
            get {
                return ResourceManager.GetString("Sin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square Root.
        /// </summary>
        internal static string Sqrt {
            get {
                return ResourceManager.GetString("Sqrt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtraction.
        /// </summary>
        internal static string Subtract {
            get {
                return ResourceManager.GetString("Subtract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tangent.
        /// </summary>
        internal static string Tan {
            get {
                return ResourceManager.GetString("Tan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arithmetic Unary Operations.
        /// </summary>
        internal static string UnaryOperations {
            get {
                return ResourceManager.GetString("UnaryOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to ConsoleApp Calculator.
        /// </summary>
        internal static string WelcomeMessage {
            get {
                return ResourceManager.GetString("WelcomeMessage", resourceCulture);
            }
        }
    }
}
